### ISSUE TITLE
Баг в функции подключения к устройству

### ISSUE THREAD

**Issue by VictorKochetkov** [MVS-Telecom/Iridium360-Connect-Framework#13]
Устройство подключено, но происходит отключение и новое подключение. Процесс зацикливается. Приложение не работает

**Comment by VictorKochetkov** [comment]
fixed 
https://github.com/MVS-Telecom/Iridium360-Connect-Framework/commit/e0eef76fbe806bb9d215b11904dac87616e8ccfc
https://github.com/MVS-Telecom/Iridium360-Connect-Framework/commit/4296e2e0e6cda8939839f81d8a6e89838a0b6d33

**Comment by nataly280576** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [проблемы с подключением](https://trello.com/c/GTQygR8Q/48-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D1%81-%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%D0%BC)
